version: 2.1

jobs:
  build_and_deploy:
    docker:
      - image: node:12.2.0-alpine
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Build application
          command: npm run build  # Ensure this matches your build script in package.json
      - add_ssh_keys:
          fingerprints:
            - "mYbuQ+8vHZzucf7uh9IoMVML8mfAGIQsq/OHqM3I4DY"
      - run:
          name: Copy application files to the server
          command: |
            scp -o StrictHostKeyChecking=no -r ./dist/* $CIRCLECI_USER@$SERVER_IP:~/app/
      - run:
          name: Deploy application on the server
          command: |
            ssh -o StrictHostKeyChecking=no $CIRCLECI_USER@$SERVER_IP '
              # Navigate to the application directory
              cd ~/app

              # Stop and remove existing Docker container if it exists
              docker stop todo-app || true
              docker rm todo-app || true

              # Build Docker image
              docker build -t todo-app .

              # Run Docker container
              docker run -d -p 8000:8000 --name todo-app todo-app
            '

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_and_deploy
