version: 2.1

jobs:
  build:
    docker:
      - image: node:12.2.0-alpine
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run tests
          command: npm run test

  deploy:
    docker:
      - image: node:12.2.0-alpine
    steps:
      - add_ssh_keys:
          fingerprints:
            - "mYbuQ+8vHZzucf7uh9IoMVML8mfAGIQsq/OHqM3I4DY"
      - run:
          name: Deploy application to server
          command: |
            scp -o StrictHostKeyChecking=no -r ./* $CIRCLECI_USER@$SERVER_IP:/circleci/
      - run:
          name: Restart Docker container
          command: |
            ssh -o StrictHostKeyChecking=no $CIRCLECI_USER@$SERVER_IP \
              'docker stop todo-app || true && \
               docker rm todo-app || true && \
               docker run -d -p 8000:8000 -v /circleci:/usr/src/app --name todo-app node:12.2.0-alpine \
               sh -c "cd /usr/src/app && npm install && npm start"'

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
